name: "Java build"

on:
  workflow_call:

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'

      - uses: internal-marketplace/gradle-build-action@v2

      - name: Gradle build
        run: ./gradlew build | tee /tmp/gradle.log

      - name: Extract test results
        if: always()
        run: |
          grep '.*Test .*' /tmp/gradle.log > /tmp/test.results
          sed -e 's/\(.*\)\( PASSED\)/✅ \1 \2/g' -e  's/\(.*\)\( FAILED\)/❌ \1 \2/g'  -e 's/\(.*\)\( SKIPPED\)/⏩ \1 \2/g' /tmp/test.results | tee /tmp/report.md
          grep '|  Results: ' /tmp/gradle.log >> /tmp/report.md

      - name: Store build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./dist/*.zip

      - name: Store static files
        uses: actions/upload-artifact@v3
        with:
          name: report.md
          path: /tmp/report.md
          retention-days: 5

  # upload_to_artifactory:
  #   runs-on: ubuntu-latest
  #   needs: compile_gwt
  #   steps:
  #   - name: Download static files
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: static-files
  #       path: ./public/
  #   - run: cd public && zip -r ../CDA-frontend-SNAPSHOT.zip * && cd ..
# #        if ! [ "${GITHUB_REF}" = *refs/tags/* ] ; then
# #          tag="b${GITHUB_REF_NAME}";
# #        else
# #          tag="SNAPSHOT";
# #        fi
  #   - run: >-
  #       tag="SNAPSHOT"
  #       curl -H "Authorization: Bearer ${{ secrets.AES_ARTIFACTS_TOKEN }}" -T CDA-frontend-SNAPSHOT.zip "https://artifacts.rbi.tech/artifactory/aes-raw-host/CDA/CDA-frontend-${tag}.zip"
