name: Sync Files to other repositories

on:
  #push:
  #  branches:
  #    - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: rbi-ho-runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Run GitHub File Sync
        uses: internal-marketplace/repo-file-sync-action@v1.17.21
        with:
          GH_PAT: ${{ secrets.CORTEX_BOT_PAT }}
          COMMIT_EACH_FILE: false
          CONFIG_PATH: repo-sync-config.yml